USE [master]
GO

/****** Object:  Database [WorldGuru]    Script Date: 17.05.2023 10:35:58 ******/
CREATE DATABASE [WorldGuru]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WorldGuru', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WorldGuru.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WorldGuru_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WorldGuru_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WorldGuru].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WorldGuru] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WorldGuru] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WorldGuru] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WorldGuru] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WorldGuru] SET ARITHABORT OFF 
GO

ALTER DATABASE [WorldGuru] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WorldGuru] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WorldGuru] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WorldGuru] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WorldGuru] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WorldGuru] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WorldGuru] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WorldGuru] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WorldGuru] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WorldGuru] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WorldGuru] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WorldGuru] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WorldGuru] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WorldGuru] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WorldGuru] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WorldGuru] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WorldGuru] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WorldGuru] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WorldGuru] SET  MULTI_USER 
GO

ALTER DATABASE [WorldGuru] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WorldGuru] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WorldGuru] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WorldGuru] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WorldGuru] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WorldGuru] SET  READ_WRITE 
GO

